### ISSUE TITLE
屏幕X轴滚动条关闭

### ISSUE THREAD

**Issue by Silence-dream** [Silence-dream/blog#19]
```css
html {
  overflow-y: scroll;
}

:root {
  overflow-y: auto;
  overflow-x: hidden;
}
```
