### ISSUE TITLE
Video 标签样式

### ISSUE THREAD

**Issue by Silence-dream** [Silence-dream/blog#23]
```css
//全屏按钮
video::-webkit-media-controls-fullscreen-button {
  display: none;
}
//播放按钮
video::-webkit-media-controls-play-button {
  display: none;
}
//进度条
video::-webkit-media-controls-timeline {
  display: none;
}
//观看的当前时间
video::-webkit-media-controls-current-time-display {
  display: none;
}
//剩余时间
video::-webkit-media-controls-time-remaining-display {
  display: none;
}
//音量按钮
video::-webkit-media-controls-mute-button {
  display: none;
}
video::-webkit-media-controls-toggle-closed-captions-button {
  display: none;
}
//音量的控制条
video::-webkit-media-controls-volume-slider {
  display: none;
}
//所有控件
video::-webkit-media-controls-enclosure {
  display: none;
}
// 下载按钮
video::-internal-media-controls-download-button {
  display: none;
}
// 下载按钮
video::-webkit-media-controls {
  overflow: hidden !important;
}
// 下载按钮-挤出
video::-webkit-media-controls-enclosure {
  width: calc(100% + 32px);
  margin-left: auto;
}
// 设置video 标签大小
video { 
   object-fit: fill;
}
```
