### ISSUE TITLE
1920 宽度不显示横向滚动条

### ISSUE THREAD

**Issue by Silence-dream** [Silence-dream/blog#6]
```css
html {  
  overflow-y: scroll;  
}  
  
:root {  
  overflow-y: auto;  
  overflow-x: hidden;  
}  
  
body {  
  width: 100vw;  
  font-family: "\5FAE\8F6F\96C5\9ED1";  
  padding-top: 42px;  
  overflow: hidden;  
}
```

**Comment by Silence-dream** [comment]
竖向不显示
```css
html {
  scrollbar-width: none;
  ::-webkit-scrollbar {
    display: none;
  }
  -ms-overflow-style: none;
}
```
