### ISSUE TITLE
移动端点击可点击元素时，出现蓝色默认背景色

### ISSUE THREAD

**Issue by Silence-dream** [Silence-dream/blog#9]
```css
body {
  -webkit-tap-highlight-color: transparent;
}
```
